on:
  push:
    branches:
      - main
      - deployment

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - id: backend-deployment
        uses: hack4impact-calpoly/express-deployment-aws@v0.1.1
        with:
          s3-bucket: "city-farm-slo-api"
          stack-name: "city-farm-slo-api-stack"
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          SEND_EMAIL: "True"

      - run: echo API is at ${{ steps.backend-deployment.outputs.api-url }}
        shell: bash
