# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [hannah-hayashi-ci-setup-1]
  pull_request:
    branches: [hannah-hayashi-ci-setup-1]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - run: npm install
      - run: npx prettier --check .
      - run: npx eslint .
